### ISSUE TITLE
Github Action to regenerate database not working on upstream

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#55]
The Github Action we created to regenerate the database works fine on my fork, but fails on @kelle's. It's not 100% clear to me why this is, but a possibility could be related to:
https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457
https://github.com/peter-evans/create-pull-request/issues/48
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

Basically, it sounds like since we have an Action that checks for a push, and another that does a push, these are blocked from running to prevent the possibility of cycling endlessly between them (even though they are not configured to do this). 
I thought that having an open Pull Request might be blocking it, but no: merging it did not make the db generation script work. A possibility could be to disable the on-push integrity test, since we the main branch is protected from pushes anyways.

**Comment by dr-rodriguez** [comment]
It's possible that #54 will fix this, but we won't know until it is merged.

**Comment by dr-rodriguez** [comment]
Another possibility, which we can test before merging #54 is to check branch protection rules. `main` is protected from pushes, so it's possible that is why this Action is failing. We may want to relax that to allow pushes for certain users (including the user _github-actions_).

**Comment by peter-evans** [comment]
Hi! I took a quick look at this because you linked to one of my issues and I happened to see it.

I think the problem is that `git commit` fails because there is no diff. The file you are generating matches the one in the default branch already, so there is nothing to commit and push. See in the screenshot below it says `Your branch is up to date with 'origin/main'`. You need to add a check to see if there is a diff before trying to commit.

![image](https://user-images.githubusercontent.com/18365890/91789294-55888700-ec49-11ea-96e4-952eeab91a7d.png)

**Comment by dr-rodriguez** [comment]
Ah, yes that can happen and that's a good catch. Though the more recent error case is that it's trying to push to a protected branch.

**Comment by peter-evans** [comment]
Ah, apologies. I missed the latest one but I see that error now. Well in that case, can I suggest a pull request? 😄 

```yml
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/dr-rodriguez/AstrodbKit2

    - name: Generate database
      run: |
        python scripts/tutorials/generate_database.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: auto regenerating database
          branch: update-database
          title: Update database
```
